- hosts: 172.31.17.250
  tasks:
        - name: Build an image and push it to a private repo
          docker_image:
              build:
                  path: "/home/edureka/Desktop"
              name: docker.io/venkat1987cloud/retailcompany
              #tag: test
              push: true
              source: build
          register: out
        - debug:
              var: out  
        - name: start a container
          docker_container:
             name: abc-application
             image: venkat1987cloud/retailcompany
             state: started
             ports:
                 - 1234:8080
             #restart: true
          register: out
        - debug:
              var: out
             #- name: Deploying to kubernetes
        - name: Create a Deployment by reading the definition from a local file 
          command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml"    
          register: out
        - debug:
              var: out
